### ISSUE TITLE
License unclear

### ISSUE THREAD

**Issue by rekado** [brummer10/GxGuvnor.lv2#1]
The LICENSE file says GPLv3+ but the license headers say GPLv2+.

**Comment by brummer10** [comment]
Hi rekado

Those files which stated GPLv2+ are template (skeleton) files which I've written and distributed over the last years under the GPLv2+. True, I've reworked them all over the time, but leave them under the GPLv2+. So, if you wish to use them under the GPLv2 you are free to do so. If you wish to use them under the GPLv3+, well, you are free. . . 

The hole project is distributed under the GPLv3+, which allow to contain files which are under the GPLv2+ (as long it is the + version of GPLv2, which it is). 
That means, files, which stated so, are under the GPLv2+, all others without explicit License Header are under the GPLv3+.

I hope that clarify it.
regards
hermann
